Repository AnshSinghSonkhia/Futuristic-CSS-Animations, pull requests merged in 2022-10, with the labels that each got.

#3 Add Marvel Intro Animation
  Marvel Intro Animation/index.html
  Marvel Intro Animation/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#4 Add Night Sky CSS animation
  night Sky/backgroundsky.jpg
  night Sky/index.html
  night Sky/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#9 Added busy traffic animation.
  Busy traffic/Images/background.jpg
  Busy traffic/Images/mincar.png
  Busy traffic/Images/mincar2.png
  Busy traffic/Images/mincar3.png
  Busy traffic/Images/mincar4.png
  Busy traffic/Images/mincar5.png
  Busy traffic/Images/mincar6.png
  Busy traffic/Images/mincar7.png
  Busy traffic/Images/mincar8.png
  Busy traffic/Images/mincar9.png
  Busy traffic/index.html
  Busy traffic/styles.css
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#10 Added Solar Rotation animations effects
  Solar-rotaion/earth.png
  Solar-rotaion/glaxy.png
  Solar-rotaion/index.html
  Solar-rotaion/pro.png
  Solar-rotaion/readme.md
  Solar-rotaion/style.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022

#11 Added Paper Plane CSS Animation
  Paper_plane-animation/README.md
  Paper_plane-animation/index.html
  Paper_plane-animation/plane.png
  Paper_plane-animation/styles.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022, hacktoberfest-2022
